apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-05-27T02:11:30Z"
    labels:
      app: backend-g2
    name: backend-g2
    namespace: default
    resourceVersion: "943"
    uid: 2d6f1f6e-9b68-48a4-9dc6-fd8339a34307
  spec:
    clusterIP: 10.110.231.127
    clusterIPs:
    - 10.110.231.127
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31927
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: backend-g2
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-05-27T02:01:41Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "196"
    uid: c86c17ea-592e-452d-ae79-c2da57851ebf
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
